version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore HelloYogis.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output HelloYogis.csproj
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'